---
- name: Play 1 -gather and show facts for the hosts in the inv file
  hosts: servers
  gather_facts: false
  vars:
    fact_dir: ~/.ansible/facts/
  tasks:
  - name: Task 1 - create new facts directory
    file:
      path: "{{ fact_dir }}"
      state: directory

  - name: Task 2 - copy custom fact script to remote host
    copy:
      src: ~/facts/get_version.fact
      dest: "{{ fact_dir }}"
      mode: 0755
  - name: Task 3 - gather facts
    setup:
      fact_path: "{{ fact_dir }}"
  - name: Task 4 - show version
    debug:
     var: ansible_local.get_version.version

- name: Play 2 - gather and show BIG-IP-specific facts
  hosts: bigips
  gather_facts: false
  connection: local
  tasks:
  - name: Task 1 - gather BIG-IP facts
    f5networks.f5_modules.bigip_device_info:
      gather_subset: system-info
      provider:
        server: "{{ inventory_hostname }}"
        user: admin
        password: f5trn002
        validate_certs: false
    register: bigip_sys_info
  - name: Task 2 - save facts
    copy:
      content: "{{ bigip_sys_info }}"
      dest: "~/facts/{{ inventory_hostname }}.facts"
