---- 
- name: Create BIG-IP App
  hosts: bigips
  gather_facts: false
  connection: local
  vars:
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ admin_user }}"
      password: "{{ admin_password }}"
      validate_certs: false

  tasks:
  - name: Delete nodes
    bigip_node
      name: 10.10.2.1
      state: absent
  
